import type { ReceiptRecord } from "@agentcheckout/shared";

/**
 * Minimal, dependency-free PDF builder for a Travel-Rule receipt.
 * In mock mode Cleanverse has no real download token, so we render a
 * self-contained PDF from the receipt's structured travelRule fields.
 * In live mode the official Cleanverse PDF URL is used instead (see the feed).
 */

const esc = (s: string) =>
  String(s).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

const fmt = (raw: string, d = 6) => {
  const n = Number(raw);
  return Number.isFinite(n) ? (n / 10 ** d).toLocaleString("en-US", { maximumFractionDigits: d }) : raw;
};

type Item = { x: number; y: number; text: string; size?: number; bold?: boolean; gray?: boolean };

export function travelRulePdf(r: ReceiptRecord): Buffer {
  const tr = r.travelRule;
  const left = 56;
  const vx = 196;
  const asset = tr?.asset ?? r.payment.asset;

  const rows: [string, string][] = [
    ["Receipt ID", r.id],
    ["Generated", tr?.generatedAt ?? r.ts],
    ["Rule version", tr?.ruleVersion ?? "-"],
    ["Network", r.payment.network],
    ["Asset", asset],
    [
      "Amount",
      `${fmt(tr?.amount ?? r.payment.amount)} ${asset}${tr?.amountUsd ? `  (~$${tr.amountUsd})` : ""}`,
    ],
    ["Originator", tr?.originator.address ?? r.payer],
    ["A-Pass principal", tr?.originator.apassPrincipal ?? r.apass.principal ?? "-"],
    [
      "A-Pass identity",
      r.apass.verified ? `verified${r.apass.tier ? `, tier ${r.apass.tier}` : ""}` : "not verified",
    ],
    [
      "Beneficiary",
      `${tr?.beneficiary.name ? `${tr.beneficiary.name}  ·  ` : ""}${tr?.beneficiary.address ?? "-"}`,
    ],
    ["Settlement tx", r.settlement.txHash ?? "-"],
  ];

  const items: Item[] = [
    { x: left, y: 790, text: "Travel Rule Receipt", size: 20, bold: true },
    { x: left, y: 770, text: "Cleanverse-compatible compliance record  ·  AgentCheckout", size: 10, gray: true },
  ];

  let y = 728;
  for (const [label, value] of rows) {
    items.push({ x: left, y, text: label.toUpperCase(), size: 8, gray: true, bold: true });
    items.push({ x: vx, y, text: value, size: 9 });
    y -= 27;
  }
  items.push({
    x: left,
    y: 70,
    text: "Generated by AgentCheckout. In production this is the official Cleanverse Travel-Rule PDF.",
    size: 8,
    gray: true,
  });

  let cs = "0.82 0.82 0.82 RG 0.7 w\n56 752 m 539 752 l S\n56 92 m 539 92 l S\nBT\n";
  for (const it of items) {
    const f = it.bold ? "/F2" : "/F1";
    const col = it.gray ? "0.46 0.46 0.46 rg" : "0.12 0.12 0.12 rg";
    cs += `${col} ${f} ${it.size ?? 10} Tf 1 0 0 1 ${it.x} ${it.y} Tm (${esc(it.text)}) Tj\n`;
  }
  cs += "ET";

  const objs: Record<number, string> = {
    1: "<< /Type /Catalog /Pages 2 0 R >>",
    2: "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    3: "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
    4: `<< /Length ${Buffer.byteLength(cs, "latin1")} >>\nstream\n${cs}\nendstream`,
    5: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    6: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
  };

  let pdf = "%PDF-1.4\n";
  const off: Record<number, number> = {};
  for (let i = 1; i <= 6; i++) {
    off[i] = Buffer.byteLength(pdf, "latin1");
    pdf += `${i} 0 obj\n${objs[i]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(pdf, "latin1");
  pdf += "xref\n0 7\n0000000000 65535 f \n";
  for (let i = 1; i <= 6; i++) pdf += `${String(off[i]).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  return Buffer.from(pdf, "latin1");
}
